//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTree.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessagesException_pt_BR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException_pt_BR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WorkTree.Exceptions.ResourceMessagesException_pt_BR", typeof(ResourceMessagesException_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        internal static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        internal static string VALIDATION_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_INVALID", resourceCulture);
            }
        }
        
        internal static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        internal static string VALIDATION_PASSWORD_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        internal static string VALIDATION_TENANT_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_TENANT_REQUIRED", resourceCulture);
            }
        }
        
        internal static string ORGANIZATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORGANIZATION_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string USER_WITH_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_WITH_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string ORGANIZATION_WITH_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ORGANIZATION_WITH_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        internal static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
    }
}
