name: CI

on:
  push:
    branches:
      - develop
    
jobs:
  build-and-test:
    name: Build & Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Installing .NET SDK
        uses: actions/setup-dotnet@v4
      
      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet test --settings tests/coverlet.runsettings
      
      - name: Publish Code Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: '**/coverage.cobertura.xml'