name: CI

on:
  push:
    branches:
      - develop
    
    pull_requests:
      branches:
        - develop

jobs:
  build-and-test:
    name: Build & Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gustavosalviato/worktree
          